#!/bin/sh

log() {
  STRAP_STEP="$*"
  echo "--> $*"
}

check_if_line_exists()
{
  log "Checking for: $LINE_TO_ADD"
  # grep wont care if one or both files dont exist.
  grep -qsFx "$LINE_TO_ADD" ~/.profile ~/.bash_profile ~/.bashrc ~/.zshrc
}

add_line_to_profile()
{
  profile=$(get_profile_file)
  log "Adding $LINE_TO_ADD to $profiles"
  printf "%s\n" "$LINE_TO_ADD" >> "$profile"
  source $profile
}

get_profile_file()
{
  profile=~/.profile
  [ -f "$profile" ] || profile=~/.bash_rc
  [ -f "$profile" ] || profile=~/.zshrc
  [ -f "$profile" ] || profile=~/.bash_profile
  [ -f "$profile" ] || profile=~/.profile
  [ -f "$profile" ] || touch $profile
  echo $profile  	
}

cd ~/

# Adding homebrew to PATH
echo "Adding Homebrew to PATH"
HOMEBREW_PREFIX=/opt/homebrew
[ -d $HOMEBREW_PREFIX ] || HOMEBREW_PREFIX=/usr/local/linuxbrew
LINE_TO_ADD="export PATH=\$PATH:${HOMEBREW_PREFIX}/bin"
check_if_line_exists || add_line_to_profile

# Turning Terminal color on
LINE_TO_ADD="export CLICOLOR=1
alias ls='ls -G'
alias ll='ls -lG'"
check_if_line_exists || add_line_to_profile

if [ ! -d .nvm ]; then
  echo "Installing nvm"
  git clone https://github.com/nvm-sh/nvm.git .nvm
  cd ~/.nvm

  . ./nvm.sh
  echo "export NVM_DIR=\"\$HOME/.nvm\"
  [ -s \"\$NVM_DIR/nvm.sh\" ] && \\. \"\$NVM_DIR/nvm.sh\"  # This loads nvm
  [ -s \"\$NVM_DIR/bash_completion\" ] && \. \"\$NVM_DIR/bash_completion\"  # This loads nvm bash_completion" >> ~/.profile

  cd ~/
  nvm install --lts

  source ~/.profile
fi

if ! grep -q "[[ -r \"$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh\" ]] && . \"$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh\"" ~/.profile; then
	echo "\n [[ -r \"$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh\" ]] && . \"$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh\"" >> ~/.profile
fi
