#!/bin/sh

cd ~/

if [ ! -d .nvm ]; then
  echo "Installing nvm"
  git clone https://github.com/nvm-sh/nvm.git .nvm
  cd ~/.nvm

  . ./nvm.sh
  echo "export NVM_DIR=\"\$HOME/.nvm\"
  [ -s \"\$NVM_DIR/nvm.sh\" ] && \\. \"\$NVM_DIR/nvm.sh\"  # This loads nvm
  [ -s \"\$NVM_DIR/bash_completion\" ] && \. \"\$NVM_DIR/bash_completion\"  # This loads nvm bash_completion" >> ~/.profile

  cd ~/
  nvm install --lts

  source ~/.profile
fi

if ! grep -q "[[ -r \"$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh\" ]] && . \"$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh\"" ~/.profile; then
	echo "\n [[ -r \"$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh\" ]] && . \"$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh\"" >> ~/.profile
fi

sudo apt install python3-venv
