#!/bin/sh
# Run by Strap after installing Brewfile dependencies
get_profile_file()
{
  profile=~/.profile
  [ -f "$profile" ] || profile=~/.bash_rc
  [ -f "$profile" ] || profile=~/.zshrc
  [ -f "$profile" ] || profile=~/.bash_profile
  [ -f "$profile" ] || profile=~/.profile
  [ -f "$profile" ] || touch $profile
  
  echo $profile  	
}

echo "Profile file: $(get_profile_file)"
. $(get_profile_file)
# sudo apt install -y python3-venv

echo "Installing VSCode plugins"
plugins=$(wget -O - -o /dev/null https://raw.githubusercontent.com/slobodnic/dev-strap/main/required/vs-plugins.txt)
for p in ${plugins[@]}; do 
  echo "-- Installing $p"
  code --install-extension $p
done
# while read -r line; do code --install-extensions "$line"; done < $plugins
